EXPECTED_COLUMNS = {
    "markets": [
        "PlatCode",
        "PlatName",
        "PlatformType",
        "AgeDays",
        "OperStatus",
        "RepScore",
        "ConfidenceLevel",
        "SizeCat",
        "DayTxnVol",
        "ActiveUsersMo",
        "SellerCount",
        "AcqCount",
        "ItemListings",
        "lastUpdated",
        "RefreshHrs",
        "platform_compliance",
    ],
    "vendors": [
        "SellerKey",
        "DaysActive",
        "PerformanceRating",
        "TotalTxns",
        "CompletedTxns",
        "DisputedEvents",
        "VerTier",
        "LastActiveDt",
        "AccessLevel",
        "InvestigationFlag",
        "LE_Interest",
        "ComplianceRisk",
        "RegStandeff",
        "vendor_compliance_ratings",
    ],
    "buyers": [
        "AcqCode",
        "ProfileAge",
        "PurchaseCount",
        "AuthLevel",
        "buyer_risk_profile",
    ],
    "products": [
        "ProdCat",
        "Subcategory",
        "ListingAge",
        "SellerPointer",
        "product_availability",
    ],
    "transactions": [
        "EventCode",
        "RecordTag",
        "EventTimestamp",
        "PlatformKey",
        "VendorLink",
        "AcqLink",
        "OriginRegion",
        "DestRegion",
        "CrossBorder",
        "RouteComplex",
        "Transaction_Velocity",
        "Border_cross_border_pre",
        "GeoDistScore",
        "transaction_financials",
    ],
    "transaction_products": [
        "EventLink",
        "ProdCat",
        "Subcategory",
        "ListingAge",
        "SellerPointer",
        "PriceAmt",
        "QtySold",
    ],
    "BuyerSessionAnalytics": [
        "BSA_id",
        "acq_ref",
        "session_start_time",
        "session_duration_seconds",
        "pages_viewed_count",
        "products_viewed_count",
        "cart_additions_count",
        "cart_removals_count",
        "search_queries_count",
        "checkout_initiated",
        "checkout_completed",
        "bounce_indicator",
        "referral_source",
        "device_category",
        "geo_region",
        "avg_time_per_page_seconds",
        "click_through_rate",
        "scroll_depth_pct",
        "error_encounters_count",
        "session_value_estimate",
    ],
    "PaymentProcessingEvents": [
        "PPE_id",
        "transaction_ref",
        "event_timestamp",
        "payment_method_type",
        "processing_stage",
        "amount_requested",
        "amount_processed",
        "currency_code",
        "processor_name",
        "authorization_code",
        "processing_fee",
        "processing_fee_pct",
        "fraud_check_passed",
        "fraud_score",
        "avs_response_code",
        "cvv_verification_passed",
        "three_ds_authenticated",
        "decline_reason",
        "retry_count",
        "processing_time_ms",
    ],
    "risk_analytics": [
        "TxnLink",
        "RiskIndicatorCount",
        "FraudProb",
        "ML_Risk",
        "LinkedEvents",
        "ChainLength",
        "wallet_risk_assessment",
    ],
    "RiskModelPredictions": [
        "RMP_id",
        "txn_link_ref",
        "prediction_timestamp",
        "model_name",
        "model_version",
        "fraud_probability",
        "risk_category_predicted",
        "confidence_score",
        "top_risk_factor",
        "risk_factors_count",
        "feature_importance_velocity",
        "feature_importance_amount",
        "feature_importance_device",
        "feature_importance_behavior",
        "recommendation_action",
        "actual_outcome",
        "prediction_latency_ms",
        "ensemble_agreement_rate",
        "manual_review_triggered",
        "model_drift_indicator",
    ],
}

PRIMARY_KEYS = {
    "markets": ["PlatCode"],
    "vendors": ["SellerKey"],
    "buyers": ["AcqCode"],
    "products": ["ProdCat", "Subcategory", "ListingAge", "SellerPointer"],
    "transactions": ["EventCode"],
    "transaction_products": [
        "EventLink",
        "ProdCat",
        "Subcategory",
        "ListingAge",
        "SellerPointer",
    ],
    "BuyerSessionAnalytics": ["BSA_id"],
    "PaymentProcessingEvents": ["PPE_id"],
    "risk_analytics": ["TxnLink"],
    "RiskModelPredictions": ["RMP_id"],
}

EXPECTED_TYPES = {
    "markets": [
        "text",
        "text",
        "text",
        "bigint",
        "text",
        "text",
        "text",
        "text",
        "real",
        "text",
        "bigint",
        "bigint",
        "bigint",
        "timestamp without time zone",
        "bigint",
        "jsonb",
    ],
    "vendors": [
        "text",
        "bigint",
        "real",
        "text",
        "bigint",
        "bigint",
        "text",
        "timestamp without time zone",
        "text",
        "text",
        "text",
        "text",
        "text",
        "jsonb",
    ],
    "buyers": ["text", "bigint", "bigint", "text", "jsonb"],
    "products": ["text", "text", "bigint", "text", "jsonb"],
    "transactions": [
        "text",
        "text",
        "timestamp without time zone",
        "text",
        "text",
        "text",
        "text",
        "text",
        "bigint",
        "text",
        "text",
        "text",
        "text",
        "jsonb",
    ],
    "transaction_products": [
        "text",
        "text",
        "text",
        "bigint",
        "text",
        "real",
        "bigint",
    ],
    "BuyerSessionAnalytics": [
        "text",
        "text",
        "timestamp without time zone",
        "integer",
        "integer",
        "integer",
        "integer",
        "integer",
        "integer",
        "boolean",
        "boolean",
        "boolean",
        "text",
        "text",
        "text",
        "real",
        "real",
        "real",
        "integer",
        "real",
    ],
    "PaymentProcessingEvents": [
        "text",
        "text",
        "timestamp without time zone",
        "text",
        "text",
        "real",
        "real",
        "text",
        "text",
        "text",
        "real",
        "real",
        "boolean",
        "real",
        "text",
        "boolean",
        "boolean",
        "text",
        "integer",
        "integer",
    ],
    "risk_analytics": ["text", "bigint", "real", "text", "bigint", "bigint", "jsonb"],
    "RiskModelPredictions": [
        "text",
        "text",
        "timestamp without time zone",
        "text",
        "text",
        "real",
        "text",
        "real",
        "text",
        "integer",
        "real",
        "real",
        "real",
        "real",
        "text",
        "text",
        "integer",
        "real",
        "boolean",
        "real",
    ],
}

TABLES = frozenset(EXPECTED_COLUMNS)

DIMENSION_TABLES = ("markets", "vendors", "buyers", "products")
FACT_TABLES = (
    "transactions",
    "transaction_products",
    "BuyerSessionAnalytics",
    "PaymentProcessingEvents",
    "risk_analytics",
    "RiskModelPredictions",
)
JSON_COLUMNS = {
    "markets": "platform_compliance",
    "vendors": "vendor_compliance_ratings",
    "buyers": "buyer_risk_profile",
    "products": "product_availability",
    "transactions": "transaction_financials",
    "risk_analytics": "wallet_risk_assessment",
}
