connector.name=postgresql
connection-url=jdbc:postgresql://postgres-source:5432/${ENV:POSTGRES_SOURCE_DB}
connection-user=${ENV:POSTGRES_SOURCE_USER}
connection-password=${ENV:POSTGRES_SOURCE_PASSWORD}
