connector.name=postgresql
connection-url=jdbc:postgresql://postgres-delivery:5432/${ENV:DELIVERY_POSTGRES_DB}
connection-user=${ENV:DELIVERY_POSTGRES_USER}
connection-password=${ENV:DELIVERY_POSTGRES_PASSWORD}
